### ISSUE TITLE
crashes when go to definition is invoked

### ISSUE THREAD

**Issue by bfranklyn** [FallenMax/naive-definitions#1]
OS: 
![windowsversion](https://user-images.githubusercontent.com/6205670/36908808-5d1b5d7c-1e0a-11e8-81a7-6973925bd9eb.png)

VS Code: 
![version](https://user-images.githubusercontent.com/6205670/36908827-6cb9618e-1e0a-11e8-8564-6e7b1c7f770c.png)

Console output: 
![message](https://user-images.githubusercontent.com/6205670/36908898-9c844c9e-1e0a-11e8-8eb4-7838d11b772a.png)

**Comment by FallenMax** [comment]
@bfranklyn Sorry for responding late. Windows compatibility is fixed in 0.0.6.
